- id: lint
  name: Lint JS(X) & TS(X)
  entry: eslint
  language: node
  args:
    - '--fix'
  additional_dependencies:
    - '@paulhfischer/prettier-config@1.2.0'
    - '@typescript-eslint/eslint-plugin@5.15.0'
    - '@typescript-eslint/parser@5.15.0'
    - eslint@8.11.0
    - eslint-config-airbnb@19.0.4
    - eslint-config-airbnb-typescript@16.1.4
    - eslint-config-prettier@8.5.0
    - eslint-plugin-html@6.2.0
    - eslint-plugin-import@2.25.4
    - eslint-plugin-jinja2-processor@1.1.0
    - eslint-plugin-jsx-a11y@6.5.1
    - eslint-plugin-prettier@4.0.0
    - eslint-plugin-react@7.29.4
    - eslint-plugin-react-hooks@4.3.0
    - prettier@2.6.0
  types:
    - file
  files: \.(js|jsx|ts|tsx|html|php)$
  exclude: (^node_modules|\.min\.js$)
