- id: lint
  name: Lint JS(X) & TS(X)
  entry: eslint
  language: node
  args:
    - '--fix'
  additional_dependencies:
    - '@paulhfischer/prettier-config@1.4.0'
    - '@typescript-eslint/eslint-plugin@5.25.0'
    - '@typescript-eslint/parser@5.25.0'
    - eslint@8.16.0
    - eslint-config-airbnb@19.0.4
    - eslint-config-airbnb-typescript@17.0.0
    - eslint-config-prettier@8.5.0
    - eslint-plugin-html@6.2.0
    - eslint-plugin-import@2.26.0
    - eslint-plugin-jinja2-processor@1.2.0
    - eslint-plugin-jsx-a11y@6.5.1
    - eslint-plugin-prettier@4.0.0
    - eslint-plugin-react@7.30.0
    - eslint-plugin-react-hooks@4.5.0
    - prettier@2.6.2
  types:
    - file
  files: \.(js|jsx|ts|tsx|html|php)$
  exclude: (^node_modules|\.min\.js$)
