- id: lint
  name: Lint JS(X) & TS(X)
  entry: eslint
  language: node
  args:
    - '--fix'
  additional_dependencies:
    - '@paulhfischer/prettier-config@1.8.0'
    - '@typescript-eslint/eslint-plugin@5.59.0'
    - '@typescript-eslint/parser@5.59.0'
    - eslint@8.39.0
    - eslint-config-airbnb@19.0.4
    - eslint-config-airbnb-typescript@17.0.0
    - eslint-config-prettier@8.8.0
    - eslint-plugin-html@7.1.0
    - eslint-plugin-import@2.27.5
    - eslint-plugin-jinja2-processor@1.2.0
    - eslint-plugin-jsx-a11y@6.7.1
    - eslint-plugin-prettier@4.2.1
    - eslint-plugin-react@7.32.2
    - eslint-plugin-react-hooks@4.6.0
    - prettier@2.8.8
  types:
    - file
  files: \.(js|jsx|ts|tsx|html|php)$
  exclude: (^node_modules|\.min\.js$)
