- id: lint
  name: Lint JS(X) & TS(X)
  entry: eslint
  language: node
  args:
    - '--fix'
  additional_dependencies:
    - '@paulhfischer/prettier-config@1.13.0'
    - '@typescript-eslint/eslint-plugin@7.18.0'
    - '@typescript-eslint/parser@7.18.0'
    - eslint@8.57.1
    - eslint-config-airbnb@19.0.4
    - eslint-config-airbnb-typescript@18.0.0
    - eslint-config-prettier@9.1.0
    - eslint-plugin-html@8.1.2
    - eslint-plugin-import@2.31.0
    - eslint-plugin-jinja2-processor@1.2.0
    - eslint-plugin-jsx-a11y@6.10.2
    - eslint-plugin-prettier@5.2.1
    - eslint-plugin-react@7.37.3
    - eslint-plugin-react-hooks@4.6.2
    - prettier@3.2.5
  types:
    - file
  files: \.(js|jsx|ts|tsx|html|php)$
  exclude: (^node_modules|\.min\.js$)
